
# reasonable item values
item.df <- data.frame(FAME=c("an","be","g00",
                             "m00","p00","s00","%00",
                             "g01","g02","g03",
                             "%01",
                             "%02","%03","m01","m02","m03","p01","p02",
                             "p03","s01","s02","s03"),
                      tsdb=c("answers","staff_count","neutral","negative",
                             "positive","balance",
                             "share",
                             "neutral_X12_D11","neutral_X12_D12",
                             "neutral_X12_E2",
                             "share_X12_D11","share_X12_D12",
                             "share_X12_E2",
                             "negative_X12_D11",
                             "negative_X12_D12","negative_X12_E2","positive_X12_D11",
                             "positive_X12_D12","positive_X12_E2","balance_X12_D11",
                             "balance_X12_D12","balance_X12_E2"),
                      unit=c("count","count","percent","percent","percent",
                             "percent","percent","percent","percent","percent",
                             "percent","percent","percent",
                             "percent","percent","percent",
                             "percent","percent","percent",
                             "percent","percent","percent"),
                      de=c("Antworten","Beschäftigte","neutral","negativ",
                           "positiv","Saldo","Anteil",
                           "neutral_X12_D11","neutral_X12_D12",
                           "neutral_X12_E2",
                           "Anteil_X12_D11",
                           "Anteil_X12_12",
                           "Anteil_X12_E2",
                           "negativ_X12_D11",
                           "negativ_X12_D12","negativ_X12_E2",
                           "positiv_X12_D11","positiv_X12_D12","positiv_X12_E2",
                           "Saldo_X12_D11","Saldo_X12_D12","Saldo_X12_E2"),
                      en=c("answers","employees","neutral","negative",
                           "positive","balance","share",
                           "neutral_X12_D11","neutral_X12_D12",
                           "neutral_X12_E2",
                           "share_X12_D11",
                           "share_X12_D12",
                           "share_X12_E2",
                           "negative_X12_D11",
                           "negative_X12_D12",
                           "negative_X12_E2",
                           "positive_X12_D11",
                           "positive_X12_D12",
                           "positive_X12_E2",
                           "balance_X12_D11",
                           "balance_X12_D12",
                           "balance_X12_E2"))

# reasonable unique question identifiers...
unqQ <- structure(list(FELD = c("F_945", "F_945", "F_945", "F_946", "F_946", 
                                "F_946", "F_947", "F_947", "F_947", "F_948", "F_948", "F_948", 
                                "F_949", "F_949", "F_949", "F_950", "F_950", "F_950", "F_951", 
                                "F_951", "F_951", "F_952", "F_952", "F_952", "F_953", "F_953", 
                                "F_953", "F_954", "F_954", "F_954", "F_955", "F_955", "F_955", 
                                "F_956", "F_956", "F_956", "F_958", "F_958", "F_958", "F_959", 
                                "F_959", "F_959", "F_960", "F_960", "F_960", "F_961", "F_961", 
                                "F_961"), F_FAME = c("f1", "f1", "f1", "f2", "f2", "f2", "f3", 
                                                     "f3", "f3", "f4", "f4", "f4", "f5", "f5", "f5", "f6", "f6", "f6", 
                                                     "f7a", "f7a", "f7a", "f7b", "f7b", "f7b", "f7c", "f7c", "f7c", 
                                                     "f7d", "f7d", "f7d", "f7e", "f7e", "f7e", "f7f", "f7f", "f7f", 
                                                     "f8", "f8", "f8", "f9", "f9", "f9", "f10", "f10", "f10", "f11", 
                                                     "f11", "f11")), .Names = c("FELD", "F_FAME"), class = "data.frame", row.names = c(NA, 
                                                                                                                                       48L))
unqQ <- unique(unqQ)
unqQ.de <- data.frame(unqQ,title=c("Geschäftslage Urteil",
                        "Nachfrage letzte 3 Monate",
                        "Beschäftigte Urteil",
                        "Technische Kapazitäten Urteil",
                        "Ertragslage letzte 3 Monate",
                        "Wettbewerbsposition letzte 3 Monate",
                        "Leistungshemmnisse ",
                        "Leistungshemmnisse ",
                        "Leistungshemmnisse ",
                        "Leistungshemmnisse ",
                        "Leistungshemmnisse ",
                        "Leistungshemmnisse ",
                        "Nachfrage nächste 3 Monate",
                        "Beschäftigte nächste 3 Monate",
                        "Preise nächste 3 Monate",
                        "Geschäftslage nächste 3 Monate"),
                      item_levels=c("keine Angabe, gut, befriedigend, schlecht",
                                    "keine Angabe, gut, befriedigend, schlecht",
                                    "keine Angabe, gut, befriedigend, schlecht",
                                    "keine Angabe, gut, befriedigend, schlecht",
                                    "keine Angabe, gut, befriedigend, schlecht",
                                    "keine Angabe, gut, befriedigend, schlecht",
                                    "keine Angabe, ungenügende Nachfrage",
                                    "keine Angabe, Mangel an Arbeitskräften",
                                    "keine Angabe, unzureichende technische Kapazitäten",
                                    "keine Angabe, wirtschaftliche und gesetzliche Rahmenbedingungen",
                                    "keine Angabe, Finanzierungsengpässe",
                                    "keine Angabe, keine Hemmnisse",
                                    "keine Angabe, gut, befriedigend, schlecht",
                                    "keine Angabe, gut, befriedigend, schlecht",
                                    "keine Angabe, gut, befriedigend, schlecht",
                                    "keine Angabe, gut, befriedigend, schlecht"
                                    ),
                      weighting_information = "Beschäftigungsgewicht (capped)"
                      )

unqQ.de <- as.matrix(unqQ.de)

# english

unqQ.en <- data.frame(unqQ,title=c("Business situation assessment",
                                   "Demand last 3 months",
                                   "Employment last 3 months",
                                   "Capacity utilization assessment",
                                   "Profit situation last 3 months",
                                   "competitive situation last 3 months",
                                   "constraints ",
                                   "constraints ",
                                   "constraints ",
                                   "constraints ",
                                   "constraints ",
                                   "constraints ",
                                   "Demand next 3 months",
                                   "Employment next 3 months",
                                   "Pricing next 3 months",
                                   "Business situation next 3 months"),
                      item_levels=c("NA, positive, satisfactory, negative",
                                    "NA, positive, satisfactory, negative",
                                    "NA, positive, satisfactory, negative",
                                    "NA, positive, satisfactory, negative",
                                    "NA, positive, satisfactory, negative",
                                    "NA, positive, satisfactory, negative",
                                    "NA, insufficient demand",
                                    "NA, insufficient workforce",
                                    "NA, insufficient technical capacity",
                                    "NA, economic and legal restrictions",
                                    "NA, financial restrictions",
                                    "NA, no restrictions",
                                    "NA, positive, satisfactory, negative",
                                    "NA, positive, satisfactory, negative",
                                    "NA, positive, satisfactory, negative",
                                    "NA, positive, satisfactory, negative"
                      ),
                      weighting_information = "Employment weighted (capped)"
)

unqQ.en <- as.matrix(unqQ.en)
